Django/Django_과목평가대비/1004/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

Django/Django_과목평가대비/1004/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/detail/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
]

Django/Django_과목평가대비/1004/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

Django/Django_과목평가대비/1004/accounts/models.py
from django.db import models

# Create your models here.

Django/Django_과목평가대비/1004/articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

Django/Django_과목평가대비/1004/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)

Django/Django_과목평가대비/1004/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = '__all__'

Django/Django_과목평가대비/1004/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .forms import CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash

# Create your views here.
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            print(request.GET.get('next'))
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)
        

@require_POST
def logout(request):
    auth_logout(request)
    return redirect('articles:index')


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect('articles:index')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

Django/Django_과목평가대비/1004/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.views.decorators.http import require_POST, require_http_methods

# Create your views here.
def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)


@require_http_methods(['GET', 'POST'])
def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form,
    }
    return render(request, 'articles/update.html', context)


@require_POST
def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.delete()
    return redirect('articles:index')

Django/Django_과목평가대비/1004/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1>Change Password</h1>
<hr>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock content %}

Django/Django_과목평가대비/1004/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Login</h1>
<hr>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock content %}

Django/Django_과목평가대비/1004/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Signup</h1>
<hr>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock content %}

Django/Django_과목평가대비/1004/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<h1>Update</h1>
<hr>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock content %}

Django/Django_과목평가대비/1004/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
<h1>CREATE</h1>
<hr>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="" id="">
</form>
{% endblock content %}

Django/Django_과목평가대비/1004/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>DETAIL</h1>
<hr>
<h3>{{ article.pk }}번째 글</h3>
<p>제목: {{ article.title }}</p>
<p>내용: {{ article.content }}</p>
<p>생성일: {{ article.created_at }}</p>
<p>수정일: {{ article.updated_at }}</p>
<hr>
<a href="{% url 'articles:index' %}">[Back]</a>
<a href="{% url 'articles:update' article.pk %}">[Update]</a>
<form action="{% url 'articles:delete' article.pk %}">
  {% csrf_token %}
  <input type="submit" value="Delete">
</form>
{% endblock content %}

Django/Django_과목평가대비/1004/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<h1>INDEX</h1>
<hr>
{% for article in articles %}
  <p>{{ article.pk }}번째 글</p>
  <h4>제목: {{ article.title }}</h4>
  <p>생성일: {{ article.created_at|date:"DATETIME_FORMAT" }}</p>
  <p>수정일: {{ article.updated_at|date:"DATETIME_FORMAT" }}</p>
  <a href="{% url 'articles:detail' article.pk %}">Detail</a>
  <hr>
{% endfor %}
{% endblock content %}

Django/Django_과목평가대비/1004/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
<h1>UPDATE</h1>
<hr>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="" id="">
</form>
{% endblock content %}

Django/Django_과목평가대비/1004/crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <title>1004_CRUD</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'articles:index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'articles:create' %}">New</a>
        </li>
        {% if not request.user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Singup</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
        {% else %}
          <li class="nav-item active">
            <form action="{% url 'accounts:logout' %}" method="POST">
              {% csrf_token %}
              <input type="submit" value="Logout">
            </form>
          </li>
          <li class="nav-item active">
            <form action="{% url 'accounts:delete' %}" method="POST">
              {% csrf_token %}
              <input type="submit" value="회원탈퇴">
            </form>
            <a href="{% url 'accounts:update' %}">회원정보수정</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>  
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>